### ISSUE TITLE
[BUG] Korean phone mask incorrect

### ISSUE THREAD

**Issue by yachsil** [leviFrosty/witness-work#195]
**Describe the bug**
+82 (한국) 전화번호가 기입될 자리수가 부족합니다. 
한국은 010-5452-5777 이런 형식을 사용합니다. 

번역을 도와줄 수 있습니다. 
저도 프로그래머입니다. 

감사합니다. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (Draw on images if possible)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 15 Pro Max]
- OS: [e.g. iOS 17.1.2]
- Version [e.g. 1.9.0]

**Additional context**

**Comment by leviFrosty** [comment]
@yachsil 

Thanks for this bug report. I have taken a look into this and see the issue you're saying.

Since this feature comes from a third-party library it may take some time for them to merge my fix into production. If it takes longer than a few months, I may update this myself and resolve the issue.

Thank you for your patience and apologies for this!

Yours,
Levi

**Comment by leviFrosty** [comment]
Good news, the library has been updated and this will be resolved in the next App update!

Thanks for your patience.

Yours,
Levi
