### ISSUE TITLE
iPad and iPhone interworking

### ISSUE THREAD

**Issue by ksj3121** [leviFrosty/witness-work#206]
I use this app really well. I hope that if I record my time on my iPhone, I can connect to my iPad and record my time at the same time

**Comment by leviFrosty** [comment]
Hi! Thanks for writing in a ticket. Apologies for the delayed response.

Due to the nature of how Witness Work is developed, I will not be supporting cloud-sync. For security, performance, and internationalization reasons - I have chosen not to enable cloud-sync functionality.

Currently however there exists functionality in the app to "Export" & "Import" your data. Not ideal for realtime syncing, but this is something that I've spent much time deliberating over.

Thank you! I hope you understand and have a great day :) Feel free to ask any other questions or express concerns by replying here.

Yours,
Levi
